version: "1.0.0"

services:
  db:
    container_name: athena_db_container
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_DB: athena_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/athena/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/athena/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "admin",
          "-d",
          "athena_db",
          "-h",
          "localhost",
        ]
      interval: 5s
      retries: 5

volumes:
  db-data:
